DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pool_size') THEN
        CREATE TYPE pool_size AS ENUM ('_50', '_25');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'rank') THEN
        CREATE TYPE rank AS ENUM ('MS', 'CMS', 'I_A', 'II_A', 'III_A', 'I_Y', 'II_Y', 'III_Y', 'NR');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'distance') THEN
        CREATE TYPE distance AS ENUM (
            '_50_BUTTERFLY', '_50_BACKSTROKE', '_50_BREASTSTROKE', '_50_FREESTYLE',
            '_100_BUTTERFLY', '_100_BACKSTROKE', '_100_BREASTSTROKE', '_100_MEDLEY',
            '_100_FREESTYLE', '_200_BUTTERFLY', '_200_BACKSTROKE', '_200_BREASTSTROKE',
            '_200_FREESTYLE', '_200_MEDLEY', '_400_FREESTYLE', '_400_MEDLEY',
            '_800_FREESTYLE', '_1500_FREESTYLE'
        );
    END IF;
END $$;


CREATE TABLE IF NOT EXISTS POOL (
  ID BIGSERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  POOL_SIZE POOL_SIZE
);

CREATE TABLE IF NOT EXISTS SPORTS_SCHOOL (
  ID BIGSERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  POOL_ID BIGINT REFERENCES POOL(ID)
);

CREATE TABLE IF NOT EXISTS COMPETITION (
  ID BIGSERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  POOL_ID BIGINT REFERENCES POOL(ID),
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  DISTANCE DISTANCE
);

CREATE INDEX idx_competition_pool_id ON COMPETITION(POOL_ID);

CREATE TABLE IF NOT EXISTS SPORTSMAN (
  ID BIGSERIAL PRIMARY KEY,
  FULL_NAME TEXT NOT NULL,
  YOB DATE NOT NULL,
  RANK RANK,
  SPORTSCHOOL_ID BIGINT REFERENCES SPORTS_SCHOOL(ID)
);

CREATE INDEX idx_sportsman_sportschool_id ON SPORTSMAN(SPORTSCHOOL_ID);

CREATE TABLE IF NOT EXISTS ENTRY (
  COMPETITION_ID BIGINT REFERENCES COMPETITION(ID),
  SPORTSMAN_ID BIGINT REFERENCES SPORTSMAN(ID),
  PRIMARY KEY (COMPETITION_ID, SPORTSMAN_ID)
);

CREATE TABLE IF NOT EXISTS COACH (
  ID BIGSERIAL PRIMARY KEY,
  FULL_NAME TEXT NOT NULL,
  YOB DATE NOT NULL,
  SPORTSCHOOL_ID BIGINT REFERENCES SPORTS_SCHOOL(ID)
);

CREATE TABLE IF NOT EXISTS RESULT (
  ID BIGSERIAL PRIMARY KEY,
  SPORTSMAN_ID BIGINT REFERENCES SPORTSMAN(ID),
  DISTANCE DISTANCE,
  TIME INTERVAL DEFAULT '0 MINUTE_SECOND',
  COMPETITION_ID BIGINT REFERENCES COMPETITION(ID),
  RANK RANK
);

CREATE TABLE IF NOT EXISTS MEDICAL_CHECKUP (
  ID BIGSERIAL PRIMARY KEY,
  DATE DATE NOT NULL,
  SPORTSMAN_ID BIGINT REFERENCES SPORTSMAN(ID),
  DOPING_CHECK BOOLEAN
);

CREATE TABLE IF NOT EXISTS TRAINING (
  ID BIGSERIAL PRIMARY KEY,
  COACH_ID BIGINT REFERENCES COACH(ID),
  SPORTSMAN_ID BIGINT REFERENCES SPORTSMAN(ID)
);

CREATE TABLE IF NOT EXISTS TRAINING_EVENT (
  SPORTSMAN_ID BIGINT REFERENCES SPORTSMAN(ID),
  COACH_ID BIGINT REFERENCES COACH(ID),
  TRAINING_ID BIGINT REFERENCES TRAINING(ID),
  PRIMARY KEY (SPORTSMAN_ID, COACH_ID, TRAINING_ID)
);

CREATE TABLE IF NOT EXISTS EXERCISE (
  ID BIGSERIAL PRIMARY KEY,
  DESCRIPTION TEXT,
  COUNT INTEGER DEFAULT 4,
  TRAINING_ID BIGINT REFERENCES TRAINING(ID)
);
