DROP TABLE EXERCISE;
DROP TABLE TRAINING_EVENT;
DROP TABLE TRAINING;
DROP TABLE MEDICAL_CHECKUP;
DROP TABLE RESULT;
DROP TABLE COACH;
DROP TABLE ENTRY;
DROP TABLE SPORTSMAN;
DROP TABLE COMPETITION;
DROP TABLE SPORTS_SCHOOL;
DROP TABLE POOL;


